### ISSUE TITLE
Increase the length of the title field for items

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1179]
There are items in the Spanish Legal documents campaign with item titles in excess of 300 characters. The longest one I saw had 423 characters. We should increase the length of the item title field to 500 characters.

**Comment by acdha** [comment]
I think we've already addressed this in #254 but it might be a good idea for that batch to have extra scrutiny to make sure that there aren't display issues with the increased text in that field.

**Comment by rstorey** [comment]
We need a fix for this problem which prevents items from being imported at all if the title retrieved from P1 is too long:
```

16:07:07
[2020-01-13 11:07:07,560: ERROR/ForkPoolWorker-2] Task importer.tasks.create_item_import_task[74c7b6f1-6de5-4dad-8bf8-fc816f6af37e] raised unexpected: ValidationError({'title': ['Ensure this value has at most 300 characters (it has 354).']})

16:07:07
Traceback (most recent call last):

16:07:07
File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task

16:07:07
R = retval = fun(*args, **kwargs)

16:07:07
File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 650, in __protected_call__

16:07:07
return self.run(*args, **kwargs)

16:07:07
File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 161, in _inner

16:07:07
reraise(*exc_info)

16:07:07
File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 57, in reraise

16:07:07
raise value

16:07:07
File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 156, in _inner

16:07:07
return f(*args, **kwargs)

16:07:07
File "/usr/local/lib/python3.8/site-packages/celery/app/base.py", line 487, in run

16:07:07
return task._orig_run(*args, **kwargs)

16:07:07
File "/app/importer/tasks.py", line 350, in create_item_import_task

16:07:07
item.full_clean()

16:07:07
File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1203, in full_clean

16:07:07
raise ValidationError(errors)

16:07:07
django.core.exceptions.ValidationError: {'title': ['Ensure this value has at most 300 characters (it has 354).']}
```

**Comment by rstorey** [comment]
@elainekamlley Ready for testing in dev and test. To test, import the spledox campaign content. Then I'll check the log file for errors.

**Comment by rstorey** [comment]
Need to make it longer. The longest title is 545 characters.
