### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by bkalish** [LibraryOfCongress/concordia#1350]
**What behavior did you observe? Please describe the bug**
docker-compose up failed with following errors:

```
WARNING: The POSTGRESQL_PW variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 727, in urlopen
  File "site-packages/urllib3/util/retry.py", line 403, in increment
  File "site-packages/urllib3/packages/six.py", line 734, in reraise
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 205, in _retrieve_server_version
  File "site-packages/docker/api/daemon.py", line 181, in version
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 228, in _get
  File "site-packages/requests/sessions.py", line 543, in get
  File "site-packages/requests/sessions.py", line 530, in request
  File "site-packages/requests/sessions.py", line 643, in send
  File "site-packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "site-packages/docker/api/client.py", line 188, in __init__
  File "site-packages/docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2885] Failed to execute script docker-compose
```

**How can we reproduce the bug?**
1. git clone https://github.com/LibraryOfCongress/concordia.git
2. cd concordia
3. docker-compose up

These are the instructions from https://github.com/LibraryOfCongress/concordia/blob/master/docs/for-developers.md

**What is the expected behavior?**
A working installation available at localhost

**Desktop (please complete the following information):**

-   MacOS: [e.g. iOS]

**Additional context**
This is with a fresh repository cloned from GitHub. (I gave up on the old outdated repository for which I submitted
issue #1302

**Comment by elainekamlley** [comment]
@bkalish seems like its not reading your config file. Question - are you in your pip env in your shell? Let us know if you need additional support, we could set up a meeting and walk through it.

**Comment by bkalish** [comment]
Thanks @elainekamlley. I'm not sure what it would mean to be in my "pip env". I ran the [commands](https://github.com/LibraryOfCongress/concordia/blob/master/docs/for-developers.md) from my default shell, which is Bash.

**Comment by bkalish** [comment]
In a previous failed attempt to install Concordia (#1302) I tried all sorts of tweaks, but didn't have any luck and it became hard to tell when an error might be the fault of my own changes and when it was a fault in the repo, so this time I figured I would just follow the instructions exactly and ask for help here.

I do notice that pip is not part of the system Python (2.7.16). Pyenv tells me that pip is a command in several of the other installed Pythons.

**Comment by bkalish** [comment]
Solved! Many thanks to Ranjan for helping me track this down. The database password had not being set or was being set incorrectly. We were able to fix this by

entering the concordia_db_1 container using docker exec (you can do this from the Docker dashboard without having to mess with container IDs)
launching the database frontend with psql concordia concordia
connecting to the concordia database \c concordia
changing the password with ALTER ROLE concordia WITH PASSWORD 'concordia123';
The semicolon in the last command is essential.

It would be lovely if the this were to scripted happen automatically or, at the least, if the documentation were updated to let folks know this step was necessary.

**Comment by bkalish** [comment]
Solved! Many thanks to Ranjan for helping me track this down. The database password had not being set or was being set incorrectly. We were able to fix this by

1. entering the `concordia_db_1` container using `docker exec` (you can do this from the Docker dashboard without having to mess with container IDs)
2. launching the database frontend with `psql concordia concordia`
3. connecting to the concordia database `\c concordia`
4. changing the password with `ALTER ROLE concordia WITH PASSWORD 'concordia123';`

The semicolon in the last command is essential.

It would be lovely if the this were to scripted happen automatically or, at the least, if the documentation were updated to let folks know this step was necessary.

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-36](https://staff.loc.gov/tasks/browse/CONCD-36)

**Comment by jkueloc** [comment]
Documentation was updated via [CONCD-28](https://staff.loc.gov/tasks/browse/CONCD-28)
