### ISSUE TITLE
Campaign creation should follow best practices

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/concordia#182]
There are a number of problems with the campaign creation view:

1. Create should be a standard form which performs validation and cues the tasks. Currently it fails with an unreported error and no UI feedback if the user enters a campaign/project slug which already exists.
2. The form should identify what the values are used for and what they need (e.g. currently it expects the slug values but does no input validation)
3. The successful result page (i.e. the detail page) should display the current progress information and use the AJAX updater for live status updates.

I'm marking this as P2 because we can work around the limitations here more easily than other problems.

**Comment by acdha** [comment]
This will probably be fixed by enabling Django's form validation but we should ensure it cannot be possible in the future:

```
[2018-09-17 19:36:11,875: ERROR/ForkPoolWorker-4] Task importer.tasks.download_write_item_assets[5750e606-08f5-4281-96d1-46682b49188b] raised unexpected: MultipleObjectsReturned('get() returned more than one CampaignItemAssetCount -- it returned 2!',)
Traceback (most recent call last):
  File "/Users/cadams/.virtualenvs/concordia-EbYnxbNX/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/cadams/.virtualenvs/concordia-EbYnxbNX/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/cadams/Projects/concordia/importer/tasks.py", line 216, in download_write_item_assets
    campaign_task=ctd, campaign_item_identifier=item_id
  File "/Users/cadams/.virtualenvs/concordia-EbYnxbNX/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/cadams/.virtualenvs/concordia-EbYnxbNX/lib/python3.6/site-packages/django/db/models/query.py", line 487, in get_or_create
    return self.get(**lookup), False
  File "/Users/cadams/.virtualenvs/concordia-EbYnxbNX/lib/python3.6/site-packages/django/db/models/query.py", line 407, in get
    (self.model._meta.object_name, num)
importer.models.MultipleObjectsReturned: get() returned more than one CampaignItemAssetCount -- it returned 2!
```

**Comment by acdha** [comment]
This is moot now that we've deleted that view and corrected the data model
